# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20170801_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercurso',
            name='idCurso',
        ),
        migrations.RemoveField(
            model_name='usercurso',
            name='idUsuario',
        ),
        migrations.DeleteModel(
            name='UserCurso',
        ),
    ]
